### ISSUE TITLE
basic Multi-Agent support

### ISSUE THREAD

**Issue by edunofe** [gilzamir18/AI4U#9]
Is it possible to perform multiple actions simultaneously? If not, I suggest implementing this feature.

**Comment by gilcoder** [comment]
We will add multi-agent support in version 2 AI4U, scheduled for May 2023. Before that, let's create an experimental branch of this functionality.

**Comment by gilzamir18** [comment]
Current main repo support multiple actions and multi-agente, mas not use a explicit framework for this.
